# Generated by Django 4.1 on 2023-09-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='texteditor',
            name='title',
            field=models.CharField(default=1, max_length=100, verbose_name='Заголовок'),
            preserve_default=False,
        ),
    ]
