# Generated by Django 4.1 on 2023-09-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingApp', '0002_texteditor_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='texteditor',
            options={'verbose_name': 'Редактор тексту', 'verbose_name_plural': 'Редактор текстів'},
        ),
        migrations.AddField(
            model_name='texteditor',
            name='is_selected',
            field=models.BooleanField(default=False, verbose_name='Обрано для надсилання'),
        ),
    ]
