# Generated by Django 4.1 on 2023-09-11 08:57

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_created', to=settings.AUTH_USER_MODEL, verbose_name='Створив(ла)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновив(ла)')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscrabe_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва')),
                ('token', models.CharField(max_length=255, unique=True, verbose_name='Токен')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_created', to=settings.AUTH_USER_MODEL, verbose_name='Створив(ла)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновив(ла)')),
            ],
            options={
                'verbose_name': 'Сервіс',
                'verbose_name_plural': 'Сервіси',
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/mainpage', verbose_name='Зображення')),
                ('video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Відео')),
                ('available', models.BooleanField(default=True, verbose_name='Актуальне')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Час обновлення')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainpages_created', to=settings.AUTH_USER_MODEL, verbose_name='Створив(ла)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mainpages_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновив(ла)')),
            ],
            options={
                'verbose_name': 'Головне медіа',
                'verbose_name_plural': 'Головні медіа',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('image', models.ImageField(null=True, upload_to='images/', verbose_name='Зображення')),
                ('time', models.CharField(max_length=200, verbose_name='Період')),
                ('model', models.CharField(max_length=200, verbose_name='Період')),
                ('group', models.CharField(max_length=200, verbose_name='Група')),
                ('format', models.CharField(max_length=200, verbose_name='Формат')),
                ('price_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна загальна')),
                ('price_mounth', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за місяць')),
                ('message', models.CharField(max_length=200, verbose_name='Заклик')),
                ('available', models.BooleanField(default=True, verbose_name='Наявність')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Час обновлення')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to='main.category', verbose_name='Категорія')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_created', to=settings.AUTH_USER_MODEL, verbose_name='Створив(ла)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновив(ла)')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курси',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name="Ім'я")),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('mobile_phone', models.CharField(max_length=15, verbose_name='Мобільний телефон')),
                ('description', models.CharField(blank=True, max_length=300, null=True, verbose_name='Примітка')),
                ('done', models.BooleanField(default=False, verbose_name='Оброблено')),
                ('comment', models.TextField(blank=True, max_length=400, null=True, verbose_name='Записка')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Час створення')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Час обновлення')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновив(ла)')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакти ',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=600, verbose_name='Відгук')),
                ('author', models.CharField(max_length=100, verbose_name='Автор')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_created', to=settings.AUTH_USER_MODEL, verbose_name='Створив(ла)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_updated', to=settings.AUTH_USER_MODEL, verbose_name='Обновив(ла)')),
            ],
            options={
                'verbose_name': 'Коментар',
                'verbose_name_plural': 'Коментарі',
            },
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['id', 'name'], name='main_course_id_1d45f8_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created'], name='main_course_created_0fdb79_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author'], name='main_commen_author_8838e3_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='main_catego_name_5111b9_idx'),
        ),
    ]
