# Generated by Django 4.1 on 2023-09-16 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscrabe_email',
            options={'verbose_name': 'Підписка на розсилку', 'verbose_name_plural': 'Підписки на розсилку'},
        ),
    ]
